import { CheckCircleRounded, ClearAllRounded, ContentCopyRounded, ErrorRounded, ExpandLessRounded, ExpandMoreRounded, FileDownloadRounded, HourglassTopRounded, TerminalRounded } from "@mui/icons-material";
import { Box, Chip, Divider, IconButton, InputAdornment, MenuItem, Paper, Stack, TextField, Tooltip, Typography } from "@mui/material";
import React from "react";
import { useTranslation } from "react-i18next";
import { useAppStore } from "../store";
import { shortTime } from "../utils";

export default function CommandLedger() {
  const { t } = useTranslation(); const { commands, commandPanelOpen, commandPanelHeight, toggleCommandPanel, setCommandPanelHeight } = useAppStore();
  const [source, setSource] = React.useState("all"); const [query, setQuery] = React.useState(""); const [expanded, setExpanded] = React.useState<string>(); const dragY = React.useRef<number | undefined>(undefined);
  const filtered = commands.filter((c) => (source === "all" || c.source === source) && `${c.command} ${c.stdout} ${c.hostName}`.toLowerCase().includes(query.toLowerCase()));
  React.useEffect(() => { const move = (e: MouseEvent) => { if (dragY.current !== undefined) setCommandPanelHeight(Math.max(140, Math.min(500, window.innerHeight - e.clientY))); }; const up = () => { dragY.current = undefined; }; window.addEventListener("mousemove", move); window.addEventListener("mouseup", up); return () => { window.removeEventListener("mousemove", move); window.removeEventListener("mouseup", up); }; }, [setCommandPanelHeight]);
  const copyAll = () => navigator.clipboard.writeText(filtered.map((c) => `[${c.timestamp}] ${c.hostName || "local"} $ ${c.command}\n${c.stdout}${c.stderr}`).join("\n"));
  return <Paper square elevation={4} sx={{ height: commandPanelOpen ? commandPanelHeight : 42, minHeight: commandPanelOpen ? 140 : 42, display: "flex", flexDirection: "column", borderTop: 1, borderColor: "divider", zIndex: 3 }}>
    {commandPanelOpen && <Box onMouseDown={(e) => { dragY.current = e.clientY; }} sx={{ height: 5, cursor: "ns-resize", "&:hover": { bgcolor: "primary.main" } }}/>}<Stack direction="row" alignItems="center" spacing={1} sx={{ height: 42, px: 1.5 }}><TerminalRounded fontSize="small" color="primary"/><Typography variant="subtitle2">{t("commandLog")}</Typography><Chip size="small" label={`${filtered.length} 条`} variant="outlined"/><Box sx={{ flex: 1 }}/>{commandPanelOpen && <><TextField select size="small" value={source} onChange={(e) => setSource(e.target.value)} sx={{ width: 125 }}><MenuItem value="all">全部来源</MenuItem>{["connection","monitor","firewall","sftp","forward","system"].map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField size="small" value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t("filter")} sx={{ width: 190 }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><TerminalRounded sx={{ fontSize: 16 }}/></InputAdornment> } }}/><Tooltip title={t("copy")}><IconButton size="small" onClick={copyAll}><ContentCopyRounded fontSize="small"/></IconButton></Tooltip><Tooltip title={t("export")}><IconButton size="small"><FileDownloadRounded fontSize="small"/></IconButton></Tooltip><Tooltip title={t("clear")}><IconButton size="small"><ClearAllRounded fontSize="small"/></IconButton></Tooltip></>}<IconButton size="small" onClick={toggleCommandPanel}>{commandPanelOpen ? <ExpandMoreRounded/> : <ExpandLessRounded/>}</IconButton></Stack>
    {commandPanelOpen && <><Divider/><Box sx={{ overflow: "auto", flex: 1, bgcolor: (theme) => theme.palette.mode === "dark" ? "#0A0E14" : "#F8FAFD" }}>{filtered.length ? filtered.slice().reverse().map((c) => <Box key={c.id} onClick={() => setExpanded(expanded === c.id ? undefined : c.id)} sx={{ px: 1.5, py: .7, borderBottom: 1, borderColor: "divider", cursor: "pointer", "&:hover": { bgcolor: "action.hover" } }}><Stack direction="row" spacing={1} alignItems="center">{c.status === "success" ? <CheckCircleRounded color="success" sx={{ fontSize: 16 }}/> : c.status === "error" ? <ErrorRounded color="error" sx={{ fontSize: 16 }}/> : <HourglassTopRounded color="warning" sx={{ fontSize: 16 }}/>}<Typography variant="caption" color="text.secondary" className="mono">{shortTime(c.timestamp)}</Typography><Chip label={c.hostName || "local"} size="small" sx={{ height: 20 }}/><Chip label={c.source} size="small" variant="outlined" sx={{ height: 20 }}/><Typography variant="body2" className="mono" noWrap sx={{ flex: 1 }}>$ {c.command}</Typography>{c.repeatCount > 1 && <Chip size="small" label={`×${c.repeatCount}`} sx={{ height: 20 }}/>}<Typography variant="caption" color="text.secondary">{c.durationMs} ms</Typography></Stack>{expanded === c.id && <Box sx={{ mt: .7, ml: 3.2, p: 1, borderRadius: 1, bgcolor: "#0A0E14", color: "#C9D1D9" }}><Typography component="pre" variant="caption" className="mono" sx={{ whiteSpace: "pre-wrap", m: 0 }}>{c.stdout || c.stderr || "(无输出)"}</Typography></Box>}</Box>) : <Typography variant="body2" color="text.secondary" textAlign="center" sx={{ py: 4 }}>后台命令将在这里按执行顺序显示</Typography>}</Box></>}
  </Paper>;
}
