import { AddRounded, CheckCircleRounded, DeleteOutlineRounded, GppGoodRounded, LockClockRounded, RefreshRounded, WarningAmberRounded } from "@mui/icons-material";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControlLabel, IconButton, MenuItem, Paper, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import React from "react";
import { api } from "../api";
import { useAppStore } from "../store";
import type { FirewallPlan, FirewallRuleInput, HostProfile } from "../types";
import { formatError } from "../utils";

const blankRule: FirewallRuleInput = { direction: "in", family: "both", protocol: "tcp", ports: "", source: "any", destination: "any", action: "allow", enabled: true, comment: "" };

export default function FirewallView({ host }: { host: HostProfile }) {
  const firewall = useAppStore((s) => s.firewall[host.id]); const setFirewall = useAppStore((s) => s.setFirewall);
  const [rule, setRule] = React.useState(blankRule); const [editorOpen, setEditorOpen] = React.useState(false); const [plan, setPlan] = React.useState<FirewallPlan>(); const [error, setError] = React.useState(""); const [applying, setApplying] = React.useState(false); const [deadline, setDeadline] = React.useState<string>(); const [sudoOpen, setSudoOpen] = React.useState(false); const [sudoPassword, setSudoPassword] = React.useState(""); const [rememberSudo, setRememberSudo] = React.useState(false);
  const refresh = React.useCallback(() => api.firewallRead(host.id).then(setFirewall).catch((e) => setError(formatError(e))), [host.id, setFirewall]); React.useEffect(() => { refresh(); }, [refresh]);
  const createPlan = async (operation: "add" | "delete" = "add", selectedRule = rule) => { try { setError(""); setPlan(await api.firewallPlan(host.id, selectedRule, operation)); setEditorOpen(false); } catch (e) { setError(formatError(e)); } };
  const apply = async (password?: string) => { if (!plan) return; setApplying(true); try { const result = await api.firewallApply(plan.id, password, rememberSudo) as { rollbackDeadline?: string }; setDeadline(result.rollbackDeadline); setSudoOpen(false); setSudoPassword(""); } catch (e) { if ((e as { kind?: string })?.kind === "sudoRequired") setSudoOpen(true); else setError(formatError(e)); } finally { setApplying(false); } };
  const commit = async () => { if (!plan) return; try { await api.firewallCommit(plan.id); setPlan(undefined); setDeadline(undefined); refresh(); } catch (e) { setError(formatError(e)); } };
  const rollback = async () => { if (!plan) return; try { await api.firewallRollback(plan.id); setPlan(undefined); setDeadline(undefined); refresh(); } catch (e) { setError(formatError(e)); } };
  return <Box sx={{ overflowY: "auto", height: "100%", pr: .5 }}><Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 2 }}><GppGoodRounded color={firewall?.enabled ? "success" : "disabled"}/><Typography variant="h6">系统防火墙</Typography>{firewall && <><Chip size="small" label={firewall.backend}/><Chip size="small" color={firewall.enabled ? "success" : "default"} label={firewall.enabled ? "运行中" : "已停止"}/></>}<Box sx={{ flex: 1 }}/><IconButton onClick={refresh}><RefreshRounded/></IconButton><Button variant="contained" startIcon={<AddRounded/>} onClick={() => { setRule(blankRule); setEditorOpen(true); }} disabled={!firewall?.rollbackAvailable}>添加规则</Button></Stack>
    {error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 1.5 }}>{error}</Alert>}
    {firewall && !firewall.rollbackAvailable && <Alert severity="warning" sx={{ mb: 1.5 }}>服务器没有可靠的自动回滚机制，写入操作已禁用。</Alert>}
    {firewall && <Stack direction={{ xs: "column", md: "row" }} spacing={1.5} sx={{ mb: 1.5 }}><Info label="默认入站" value={firewall.defaultInbound.toUpperCase()}/><Info label="默认出站" value={firewall.defaultOutbound.toUpperCase()}/><Info label="回滚" value={firewall.rollbackAvailable ? "可用 · 60 秒" : "不可用"}/><Info label="规则数" value={String(firewall.rules.length)}/></Stack>}
    <Paper variant="outlined" sx={{ overflow: "hidden" }}><Table><TableHead><TableRow><TableCell>状态</TableCell><TableCell>方向</TableCell><TableCell>动作</TableCell><TableCell>协议</TableCell><TableCell>端口</TableCell><TableCell>来源</TableCell><TableCell>备注</TableCell><TableCell align="right">操作</TableCell></TableRow></TableHead><TableBody>{firewall?.rules.map((item) => <TableRow key={item.id} hover><TableCell><Switch size="small" checked={item.enabled} disabled={item.readOnly}/></TableCell><TableCell>{item.direction === "in" ? "入站" : item.direction === "out" ? "出站" : "转发"}</TableCell><TableCell><Chip size="small" label={item.action.toUpperCase()} color={item.action === "allow" ? "success" : "error"} variant="outlined"/></TableCell><TableCell className="mono">{item.protocol}</TableCell><TableCell className="mono">{item.ports || "any"}</TableCell><TableCell className="mono">{item.source}</TableCell><TableCell>{item.comment}{item.readOnly && <Chip size="small" label="只读" sx={{ ml: 1 }}/>}</TableCell><TableCell align="right"><IconButton size="small" color="error" disabled={item.readOnly || !firewall?.rollbackAvailable} onClick={() => createPlan("delete", item)}><DeleteOutlineRounded fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Dialog open={editorOpen} onClose={() => setEditorOpen(false)} fullWidth maxWidth="sm"><DialogTitle>添加防火墙规则</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><Stack direction="row" spacing={1.5}><TextField select fullWidth label="方向" value={rule.direction} onChange={(e) => setRule({ ...rule, direction: e.target.value as "in" | "out" })}><MenuItem value="in">入站</MenuItem><MenuItem value="out">出站</MenuItem></TextField><TextField select fullWidth label="动作" value={rule.action} onChange={(e) => setRule({ ...rule, action: e.target.value as FirewallRuleInput["action"] })}><MenuItem value="allow">允许</MenuItem><MenuItem value="deny">丢弃</MenuItem><MenuItem value="reject">拒绝</MenuItem></TextField></Stack><Stack direction="row" spacing={1.5}><TextField select fullWidth label="协议" value={rule.protocol} onChange={(e) => setRule({ ...rule, protocol: e.target.value as FirewallRuleInput["protocol"] })}><MenuItem value="tcp">TCP</MenuItem><MenuItem value="udp">UDP</MenuItem><MenuItem value="icmp">ICMP</MenuItem><MenuItem value="any">任意</MenuItem></TextField><TextField fullWidth label="端口或范围" placeholder="80,443 或 8000:8100" value={rule.ports} onChange={(e) => setRule({ ...rule, ports: e.target.value })}/></Stack><TextField fullWidth label="来源 CIDR" value={rule.source} onChange={(e) => setRule({ ...rule, source: e.target.value })}/><TextField fullWidth label="备注" value={rule.comment} onChange={(e) => setRule({ ...rule, comment: e.target.value })}/><FormControlLabel control={<Switch checked={rule.family === "both"} onChange={(e) => setRule({ ...rule, family: e.target.checked ? "both" : "ipv4" })}/>} label="同时应用 IPv4 和 IPv6"/></Stack></DialogContent><DialogActions><Button onClick={() => setEditorOpen(false)}>取消</Button><Button variant="contained" onClick={() => createPlan()}>生成计划</Button></DialogActions></Dialog>
    <Dialog open={!!plan} onClose={() => !deadline && !applying && setPlan(undefined)} fullWidth maxWidth="md"><DialogTitle><Stack direction="row" alignItems="center" spacing={1}><LockClockRounded color="warning"/>防火墙安全变更计划</Stack></DialogTitle><DialogContent>{plan && <Stack spacing={2}><Alert severity={plan.risk === "high" ? "error" : "warning"}>{plan.summary}</Alert><Paper variant="outlined" sx={{ p: 1.5, bgcolor: "#0A0E14", color: "#D8DEE9" }}>{plan.commands.map((command, index) => <Typography key={index} className="mono" variant="body2">$ {command}</Typography>)}</Paper>{plan.warnings.map((warning, index) => <Stack key={index} direction="row" spacing={1}><WarningAmberRounded color="warning" fontSize="small"/><Typography variant="body2">{warning}</Typography></Stack>)}<Divider/>{deadline ? <Alert icon={<CheckCircleRounded/>} severity="success">SSH 验证成功，请在 60 秒内保留更改，否则将自动回滚。</Alert> : <Typography variant="body2" color="text.secondary">应用前会保存快照并建立自动回滚，状态哈希：<span className="mono">{plan.stateHash.slice(0, 16)}</span></Typography>}</Stack>}</DialogContent><DialogActions>{deadline ? <><Button color="error" onClick={rollback}>立即回滚</Button><Button variant="contained" color="success" onClick={commit}>保留更改</Button></> : <><Button onClick={() => setPlan(undefined)} disabled={applying}>取消</Button><Button variant="contained" color="warning" disabled={applying} onClick={() => apply()}>{applying ? "正在执行…" : "确认并执行"}</Button></>}</DialogActions></Dialog>
    <Dialog open={sudoOpen} onClose={() => !applying && setSudoOpen(false)} fullWidth maxWidth="xs"><DialogTitle>需要 sudo 密码</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><Alert severity="info">密码仅保存在当前连接内存中，不会写入命令记录。</Alert><TextField autoFocus fullWidth type="password" label="sudo 密码" value={sudoPassword} onChange={(e) => setSudoPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && sudoPassword && apply(sudoPassword)}/><FormControlLabel control={<Switch checked={rememberSudo} onChange={(e) => setRememberSudo(e.target.checked)}/>} label="安全记住到 Windows Credential Manager"/></Stack></DialogContent><DialogActions><Button onClick={() => setSudoOpen(false)} disabled={applying}>取消</Button><Button variant="contained" onClick={() => apply(sudoPassword)} disabled={!sudoPassword || applying}>继续执行</Button></DialogActions></Dialog>
  </Box>;
}
function Info({ label, value }: { label: string; value: string }) { return <Paper variant="outlined" sx={{ flex: 1, p: 1.5 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6">{value}</Typography></Paper>; }
