import { AddRounded, AltRouteRounded, DeleteOutlineRounded } from "@mui/icons-material";
import { Alert, Box, Button, Chip, CircularProgress, IconButton, MenuItem, Paper, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import React from "react";
import { api } from "../api";
import type { ForwardingProfile, HostProfile } from "../types";
import { formatError } from "../utils";

export default function ForwardingView({ host }: { host: HostProfile }) {
  const [profiles, setProfiles] = React.useState<ForwardingProfile[]>([]); const [adding, setAdding] = React.useState(false); const [error, setError] = React.useState(""); const [pending, setPending] = React.useState<string[]>([]);
  const [draft, setDraft] = React.useState<ForwardingProfile>({ id: "", hostId: host.id, name: "", kind: "local", bindAddress: "127.0.0.1", bindPort: 8080, targetHost: "127.0.0.1", targetPort: 80, active: false, status: "stopped" });
  React.useEffect(() => { api.forwardingList(host.id).then(setProfiles).catch((e) => setError(formatError(e))); }, [host.id]);
  const save = async () => { try { setError(""); const saved = await api.forwardingUpsert({ ...draft, id: draft.id || crypto.randomUUID(), hostId: host.id }); setProfiles((items) => [...items.filter((item) => item.id !== saved.id), saved]); setAdding(false); } catch (e) { setError(formatError(e)); } };
  const toggle = async (profile: ForwardingProfile) => { setPending((items) => [...items, profile.id]); setProfiles((items) => items.map((item) => item.id === profile.id ? { ...item, status: !profile.active ? "starting" : "stopped" } : item)); try { const updated = await api.forwardingToggle(profile.id, !profile.active); if (updated) setProfiles((items) => items.map((item) => item.id === updated.id ? updated : item)); } catch (e) { setError(formatError(e)); setProfiles((items) => items.map((item) => item.id === profile.id ? { ...item, active: false, status: "error", lastError: formatError(e) } : item)); } finally { setPending((items) => items.filter((id) => id !== profile.id)); } };
  const remove = async (profile: ForwardingProfile) => { if (!window.confirm("确认删除此端口转发配置？")) return; try { await api.forwardingDelete(profile.id); setProfiles((items) => items.filter((item) => item.id !== profile.id)); } catch (e) { setError(formatError(e)); } };
  return <Stack sx={{ height: "100%" }} spacing={1.5}><Stack direction="row" alignItems="center"><AltRouteRounded color="primary" sx={{ mr: 1 }}/><Typography variant="h6">端口转发</Typography><Box sx={{ flex: 1 }}/><Button startIcon={<AddRounded/>} variant="contained" onClick={() => setAdding(!adding)}>新建转发</Button></Stack>{error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}
    {adding && <Paper variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: "column", md: "row" }} spacing={1.5}><TextField size="small" label="名称" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/><TextField size="small" select label="类型" value={draft.kind} onChange={(e) => setDraft({ ...draft, kind: e.target.value as ForwardingProfile["kind"] })}><MenuItem value="local">本地 -L</MenuItem><MenuItem value="remote">远程 -R</MenuItem><MenuItem value="dynamic">SOCKS -D</MenuItem></TextField><TextField size="small" label="监听地址" value={draft.bindAddress} onChange={(e) => setDraft({ ...draft, bindAddress: e.target.value })}/><TextField size="small" type="number" label="监听端口" value={draft.bindPort} onChange={(e) => setDraft({ ...draft, bindPort: Number(e.target.value) })}/>{draft.kind !== "dynamic" && <><TextField size="small" label="目标主机" value={draft.targetHost} onChange={(e) => setDraft({ ...draft, targetHost: e.target.value })}/><TextField size="small" type="number" label="目标端口" value={draft.targetPort} onChange={(e) => setDraft({ ...draft, targetPort: Number(e.target.value) })}/></>}<Button variant="contained" onClick={save}>保存</Button></Stack></Paper>}
    <Paper variant="outlined" sx={{ overflow: "hidden" }}><Table><TableHead><TableRow><TableCell>状态</TableCell><TableCell>名称</TableCell><TableCell>类型</TableCell><TableCell>监听</TableCell><TableCell>目标</TableCell><TableCell>等价命令</TableCell><TableCell /></TableRow></TableHead><TableBody>{profiles.map((profile) => { const busy = pending.includes(profile.id); return <TableRow key={profile.id} hover><TableCell><Stack direction="row" alignItems="center" spacing={1}><Switch checked={profile.active} disabled={busy} onChange={() => toggle(profile)}/>{statusChip(profile, busy)}</Stack></TableCell><TableCell>{profile.name}</TableCell><TableCell><Chip size="small" label={profile.kind.toUpperCase()}/></TableCell><TableCell className="mono">{profile.bindAddress}:{profile.bindPort}</TableCell><TableCell className="mono">{profile.kind === "dynamic" ? "SOCKS5" : `${profile.targetHost}:${profile.targetPort}`}</TableCell><TableCell className="mono">ssh -{profile.kind === "local" ? "L" : profile.kind === "remote" ? "R" : "D"} {profile.bindPort}{profile.kind !== "dynamic" ? `:${profile.targetHost}:${profile.targetPort}` : ""}</TableCell><TableCell><IconButton color="error" onClick={() => remove(profile)} disabled={busy}><DeleteOutlineRounded/></IconButton></TableCell></TableRow>; })}{profiles.length === 0 && <TableRow><TableCell colSpan={7}><Typography color="text.secondary" textAlign="center" sx={{ py: 5 }}>尚未创建端口转发</Typography></TableCell></TableRow>}</TableBody></Table></Paper>
  </Stack>;
}
function statusChip(profile: ForwardingProfile, busy: boolean) { const status = busy ? "starting" : (profile.status || (profile.active ? "active" : "stopped")); if (status === "active") return <Chip size="small" color="success" label="运行中"/>; if (status === "error") return <Tooltip title={profile.lastError || "启动失败"}><Chip size="small" color="error" label="启动失败"/></Tooltip>; if (status === "starting") return <Chip size="small" color="primary" icon={<CircularProgress size={13}/>} label="正在启动"/>; return <Chip size="small" variant="outlined" label="已停止"/>; }
