import { ArrowBackRounded, ContentCopyRounded, ContentPasteRounded, CreateNewFolderRounded, DeleteOutlineRounded, DriveFileRenameOutlineRounded, FileDownloadRounded, FileUploadRounded, FolderRounded, InsertDriveFileRounded, RefreshRounded } from "@mui/icons-material";
import { Alert, Box, Breadcrumbs, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Link, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { open } from "@tauri-apps/plugin-dialog";
import React from "react";
import { api } from "../api";
import { useAppStore } from "../store";
import type { HostProfile, SftpEntry } from "../types";
import { formatBytes, formatError } from "../utils";

export default function SftpView({ host }: { host: HostProfile }) {
  const [path, setPath] = React.useState("/"); const [entries, setEntries] = React.useState<SftpEntry[]>([]); const [loading, setLoading] = React.useState(true); const [selected, setSelected] = React.useState<string[]>([]); const [error, setError] = React.useState(""); const [menu, setMenu] = React.useState<{ x: number; y: number; entry?: SftpEntry } | null>(null); const [clipboard, setClipboard] = React.useState<string[]>([]); const [rename, setRename] = React.useState<SftpEntry>(); const [newName, setNewName] = React.useState(""); const [mkdirOpen, setMkdirOpen] = React.useState(false); const [folderName, setFolderName] = React.useState(""); const upsertTransfer = useAppStore((s) => s.upsertTransfer);
  const load = React.useCallback(() => { setLoading(true); setSelected([]); api.sftpList(host.id, path).then(setEntries).catch((e) => setError(formatError(e))).finally(() => setLoading(false)); }, [host.id, path]); React.useEffect(load, [load]);
  const selectedEntries = entries.filter((e) => selected.includes(e.path)); const toggle = (p: string) => setSelected((s) => s.includes(p) ? s.filter((x) => x !== p) : [...s, p]);
  const upload = async () => { try { const picked = await open({ multiple: true, directory: false }); const files = picked ? (Array.isArray(picked) ? picked : [picked]) : []; if (files.length) await api.sftpUpload(host.id, files, path, (e) => { upsertTransfer(e.payload); if (e.payload.status === "completed") load(); }); } catch (e) { setError(formatError(e)); } };
  const download = async (paths = selected) => { try { const folder = await open({ directory: true }); if (!folder || !paths.length) return; await api.sftpDownload(host.id, paths, folder, (e) => upsertTransfer(e.payload)); } catch (e) { setError(formatError(e)); } };
  const remove = async (paths = selected) => { if (!paths.length || !window.confirm(`确认永久删除 ${paths.length} 项？`)) return; try { await api.sftpDelete(host.id, paths); load(); } catch (e) { setError(formatError(e)); } };
  const paste = async () => { if (!clipboard.length) return; try { await api.sftpCopy(host.id, clipboard, path, (e) => upsertTransfer(e.payload)); setClipboard([]); } catch (e) { setError(formatError(e)); } };
  const submitRename = async () => { if (!rename || !newName.trim()) return; try { await api.sftpRename(host.id, rename.path, `${path.replace(/\/$/, "")}/${newName.trim()}`); setRename(undefined); load(); } catch (e) { setError(formatError(e)); } };
  const submitMkdir = async () => { if (!folderName.trim()) return; try { await api.sftpMkdir(host.id, `${path.replace(/\/$/, "")}/${folderName.trim()}`); setMkdirOpen(false); setFolderName(""); load(); } catch (e) { setError(formatError(e)); } };
  const openEntry = (entry: SftpEntry) => entry.kind === "directory" && setPath(entry.path);
  return <Stack sx={{ height: "100%" }} spacing={1.5} onClick={() => setMenu(null)}><Stack direction="row" alignItems="center" spacing={1}><Typography variant="h6">SFTP 文件管理</Typography><ChipCount count={selected.length}/><Box sx={{ flex: 1 }}/><Button startIcon={<ContentCopyRounded/>} disabled={!selected.length} onClick={() => setClipboard(selected)}>复制</Button><Button startIcon={<ContentPasteRounded/>} disabled={!clipboard.length} onClick={paste}>粘贴</Button><Button startIcon={<DeleteOutlineRounded/>} color="error" disabled={!selected.length} onClick={() => remove()}>删除</Button><Button startIcon={<FileUploadRounded/>} variant="contained" onClick={upload}>上传</Button><Button startIcon={<FileDownloadRounded/>} disabled={!selected.length} onClick={() => download()}>下载</Button><Button startIcon={<CreateNewFolderRounded/>} onClick={() => setMkdirOpen(true)}>新建目录</Button><Button startIcon={<RefreshRounded/>} onClick={load}>刷新</Button></Stack>
    {error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}<Paper variant="outlined" sx={{ px: 1.5, py: 1 }}><Stack direction="row" alignItems="center" spacing={1}><Button size="small" disabled={path === "/"} onClick={() => setPath(path.split("/").slice(0, -1).join("/") || "/")}><ArrowBackRounded/></Button><Breadcrumbs>{path.split("/").filter(Boolean).reduce<{ label: string; path: string }[]>((all, part) => [...all, { label: part, path: `${all.at(-1)?.path || ""}/${part}` }], [{ label: host.name, path: "/" }]).map((part) => <Link key={part.path} component="button" color="inherit" onClick={() => setPath(part.path)}>{part.label}</Link>)}</Breadcrumbs></Stack></Paper>
    <Paper variant="outlined" sx={{ flex: 1, overflow: "auto" }} onContextMenu={(e) => { e.preventDefault(); setMenu({ x: e.clientX, y: e.clientY }); }}>{loading && <LinearProgress/>}<Table stickyHeader><TableHead><TableRow><TableCell padding="checkbox"><Checkbox checked={entries.length > 0 && selected.length === entries.length} onChange={(e) => setSelected(e.target.checked ? entries.map((x) => x.path) : [])}/></TableCell><TableCell>名称</TableCell><TableCell>大小</TableCell><TableCell>权限</TableCell><TableCell>修改时间</TableCell></TableRow></TableHead><TableBody>{entries.map((entry) => <TableRow key={entry.path} hover selected={selected.includes(entry.path)} onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); setMenu({ x: e.clientX, y: e.clientY, entry }); }} onDoubleClick={() => openEntry(entry)}><TableCell padding="checkbox"><Checkbox checked={selected.includes(entry.path)} onChange={() => toggle(entry.path)}/></TableCell><TableCell><Stack direction="row" alignItems="center" spacing={1}>{entry.kind === "directory" ? <FolderRounded color="primary"/> : <InsertDriveFileRounded color="disabled"/>}<Typography variant="body2">{entry.name}</Typography></Stack></TableCell><TableCell>{entry.kind === "directory" ? "—" : formatBytes(entry.size)}</TableCell><TableCell className="mono">{entry.permissions || "—"}</TableCell><TableCell>{entry.modifiedAt ? new Date(entry.modifiedAt).toLocaleString() : "—"}</TableCell></TableRow>)}</TableBody></Table></Paper>
    <Menu open={Boolean(menu)} onClose={() => setMenu(null)} anchorReference="anchorPosition" anchorPosition={menu ? { top: menu.y, left: menu.x } : undefined}><MenuItem onClick={() => { if (menu?.entry) openEntry(menu.entry); setMenu(null); }} disabled={!menu?.entry || menu.entry.kind !== "directory"}>打开目录</MenuItem><MenuItem onClick={() => { if (menu?.entry) download([menu.entry.path]); setMenu(null); }} disabled={!menu?.entry}>下载</MenuItem><MenuItem onClick={() => { if (menu?.entry) setClipboard([menu.entry.path]); setMenu(null); }}>复制</MenuItem><MenuItem onClick={() => { if (menu?.entry) { setRename(menu.entry); setNewName(menu.entry.name); } setMenu(null); }} disabled={!menu?.entry}>重命名</MenuItem><MenuItem onClick={() => { if (menu?.entry) remove([menu.entry.path]); setMenu(null); }} disabled={!menu?.entry} sx={{ color: "error.main" }}>删除</MenuItem><MenuItem onClick={() => { setMenu(null); load(); }}>刷新</MenuItem></Menu>
    <Dialog open={!!rename} onClose={() => setRename(undefined)}><DialogTitle>重命名</DialogTitle><DialogContent><TextField autoFocus fullWidth value={newName} onChange={(e) => setNewName(e.target.value)} sx={{ mt: 1 }}/></DialogContent><DialogActions><Button onClick={() => setRename(undefined)}>取消</Button><Button variant="contained" startIcon={<DriveFileRenameOutlineRounded/>} onClick={submitRename}>保存</Button></DialogActions></Dialog><Dialog open={mkdirOpen} onClose={() => setMkdirOpen(false)}><DialogTitle>新建目录</DialogTitle><DialogContent><TextField autoFocus fullWidth label="目录名" value={folderName} onChange={(e) => setFolderName(e.target.value)} sx={{ mt: 1 }}/></DialogContent><DialogActions><Button onClick={() => setMkdirOpen(false)}>取消</Button><Button variant="contained" onClick={submitMkdir}>创建</Button></DialogActions></Dialog>
  </Stack>;
}
function ChipCount({ count }: { count: number }) { return count ? <Typography variant="caption" color="text.secondary">已选 {count} 项</Typography> : null; }
