import ArrowBackRounded from "@mui/icons-material/ArrowBackRounded";
import ContentCopyRounded from "@mui/icons-material/ContentCopyRounded";
import ContentPasteRounded from "@mui/icons-material/ContentPasteRounded";
import CreateNewFolderRounded from "@mui/icons-material/CreateNewFolderRounded";
import DeleteOutlineRounded from "@mui/icons-material/DeleteOutlineRounded";
import DriveFileRenameOutlineRounded from "@mui/icons-material/DriveFileRenameOutlineRounded";
import FileDownloadRounded from "@mui/icons-material/FileDownloadRounded";
import FileUploadRounded from "@mui/icons-material/FileUploadRounded";
import FolderRounded from "@mui/icons-material/FolderRounded";
import InsertDriveFileRounded from "@mui/icons-material/InsertDriveFileRounded";
import RefreshRounded from "@mui/icons-material/RefreshRounded";
import { Alert, Box, Breadcrumbs, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Link, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { open } from "@tauri-apps/plugin-dialog";
import React from "react";
import { api } from "../api";
import { useAppStore } from "../store";
import type { HostProfile, SftpEntry } from "../types";
import { formatBytes, formatError } from "../utils";

export default function SftpView({ host }: { host: HostProfile }) {
  const [path, setPath] = React.useState("/"); const [entries, setEntries] = React.useState<SftpEntry[]>([]); const [loading, setLoading] = React.useState(true); const [selected, setSelected] = React.useState<string[]>([]); const [error, setError] = React.useState(""); const [menu, setMenu] = React.useState<{ x: number; y: number; entry?: SftpEntry } | null>(null); const [clipboard, setClipboard] = React.useState<{ hostId: string; paths: string[] }>(); const [rename, setRename] = React.useState<SftpEntry>(); const [newName, setNewName] = React.useState(""); const [mkdirOpen, setMkdirOpen] = React.useState(false); const [folderName, setFolderName] = React.useState(""); const [conflict, setConflict] = React.useState<{ title: string; run: (policy: "overwrite" | "skip" | "rename" | "resume") => Promise<void> }>(); const [deleteTarget, setDeleteTarget] = React.useState<string[]>(); const upsertTransfer = useAppStore((s) => s.upsertTransfer); const conflictPolicy = useAppStore((s) => s.settings?.transferConflictPolicy ?? "ask");
  const loadSequence = React.useRef(0);
  const hostGeneration = React.useRef(0);
  React.useEffect(() => { hostGeneration.current += 1; setPath("/"); setEntries([]); setSelected([]); setClipboard(undefined); setError(""); }, [host.id]);
  const load = React.useCallback(() => { const sequence = ++loadSequence.current; setLoading(true); setError(""); setSelected([]); api.sftpList(host.id, path).then((next) => { if (sequence === loadSequence.current) { setEntries(next); setError(""); } }).catch((e) => { if (sequence === loadSequence.current) setError(formatError(e)); }).finally(() => { if (sequence === loadSequence.current) setLoading(false); }); }, [host.id, path]); React.useEffect(() => { if (host.status === "connected") load(); else { setLoading(false); setEntries([]); } return () => { loadSequence.current += 1; hostGeneration.current += 1; }; }, [load, host.status]);
  const loadRef = React.useRef(load); loadRef.current = load;
  const mounted = React.useRef(true);
  React.useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const refresh = () => { if (mounted.current) loadRef.current(); };
  const selectedEntries = entries.filter((e) => selected.includes(e.path)); const toggle = (p: string) => setSelected((s) => s.includes(p) ? s.filter((x) => x !== p) : [...s, p]);
  const performUpload = async (directory: boolean, policy: "overwrite" | "skip" | "rename" | "resume") => { const generation = hostGeneration.current; try { const picked = await open({ multiple: !directory, directory }); const files = picked ? (Array.isArray(picked) ? picked : [picked]) : []; if (generation !== hostGeneration.current) return; if (files.length) await api.sftpUpload(host.id, files, path, (e) => { upsertTransfer(e.payload); if (generation === hostGeneration.current && e.payload.status === "completed") refresh(); }, policy); } catch (e) { if (generation === hostGeneration.current) setError(formatError(e)); } };
  const upload = async (directory = false) => { if (conflictPolicy === "ask") { setConflict({ title: "选择上传冲突策略", run: (policy) => performUpload(directory, policy) }); return; } await performUpload(directory, conflictPolicy); };
  const performDownload = async (paths: string[], policy: "overwrite" | "skip" | "rename" | "resume") => { const generation = hostGeneration.current; try { const folder = await open({ directory: true }); if (!folder || !paths.length || generation !== hostGeneration.current) return; await api.sftpDownload(host.id, paths, folder, (e) => { upsertTransfer(e.payload); if (generation === hostGeneration.current && e.payload.status === "completed") refresh(); }, policy); } catch (e) { if (generation === hostGeneration.current) setError(formatError(e)); } };
  const download = async (paths = selected) => { if (!paths.length) return; if (conflictPolicy === "ask") { setConflict({ title: "选择下载冲突策略", run: (policy) => performDownload(paths, policy) }); return; } await performDownload(paths, conflictPolicy); };
  const remove = async (paths = selected) => { if (paths.length) setDeleteTarget(paths); };
  const performRemove = async () => { const paths = deleteTarget; setDeleteTarget(undefined); if (!paths?.length) return; try { await api.sftpDelete(host.id, paths); refresh(); } catch (e) { setError(formatError(e)); } };
  const performPaste = async (policy: "overwrite" | "skip" | "rename" | "resume") => { if (!clipboard || clipboard.hostId !== host.id || !clipboard.paths.length) return; try { await api.sftpCopy(host.id, clipboard.paths, path, (e) => { upsertTransfer(e.payload); if (e.payload.status === "completed") refresh(); }, policy); setClipboard(undefined); } catch (e) { setError(formatError(e)); } };
  const paste = async () => { if (!clipboard || clipboard.hostId !== host.id || !clipboard.paths.length) return; if (conflictPolicy === "ask") { setConflict({ title: "选择粘贴冲突策略", run: performPaste }); return; } await performPaste(conflictPolicy); };
  const submitRename = async () => { if (!rename) return; if (!validName(newName)) { setError("请输入有效的单个文件名，不能包含路径分隔符或控制字符"); return; } try { await api.sftpRename(host.id, rename.path, `${path.replace(/\/$/, "")}/${newName.trim()}`); setRename(undefined); refresh(); } catch (e) { setError(formatError(e)); } };
  const submitMkdir = async () => { if (!validName(folderName)) { setError("请输入有效的单个目录名，不能包含路径分隔符或控制字符"); return; } try { await api.sftpMkdir(host.id, `${path.replace(/\/$/, "")}/${folderName.trim()}`); setMkdirOpen(false); setFolderName(""); refresh(); } catch (e) { setError(formatError(e)); } };
  const openEntry = (entry: SftpEntry) => entry.kind === "directory" && setPath(entry.path);
  const blocked = loading || Boolean(error) || host.status !== "connected";
  if (host.status !== "connected") return <Alert severity="info">请先连接服务器，再浏览和管理远程文件。</Alert>;
  return <Stack sx={{ height: "100%", overflow: "auto" }} spacing={1.5} onClick={() => setMenu(null)}><Stack direction="row" alignItems="center" spacing={1} useFlexGap flexWrap="wrap"><Typography variant="h6">SFTP 文件管理</Typography><ChipCount count={selected.length}/><Box sx={{ flex: 1, minWidth: 12 }}/><Button startIcon={<ContentCopyRounded/>} disabled={blocked || !selected.length} onClick={() => setClipboard({ hostId: host.id, paths: selected })}>复制</Button><Button startIcon={<ContentPasteRounded/>} disabled={blocked || !clipboard || clipboard.hostId !== host.id || !clipboard.paths.length} onClick={paste}>粘贴</Button><Button startIcon={<DeleteOutlineRounded/>} color="error" disabled={blocked || !selected.length} onClick={() => remove()}>删除</Button><Button startIcon={<FileUploadRounded/>} variant="contained" disabled={blocked} onClick={() => upload(false)}>上传文件</Button><Button startIcon={<FolderRounded/>} disabled={blocked} onClick={() => upload(true)}>上传文件夹</Button><Button startIcon={<FileDownloadRounded/>} disabled={blocked || !selected.length} onClick={() => download()}>下载</Button><Button startIcon={<CreateNewFolderRounded/>} disabled={blocked} onClick={() => setMkdirOpen(true)}>新建目录</Button><Button startIcon={<RefreshRounded/>} onClick={load}>刷新</Button></Stack>
    {error && <Alert severity="error" onClose={() => setError("")}>{error}</Alert>}<Paper variant="outlined" sx={{ px: 1.5, py: 1 }}><Stack direction="row" alignItems="center" spacing={1}><Button aria-label="返回上级目录" size="small" disabled={path === "/"} onClick={() => setPath(path.split("/").slice(0, -1).join("/") || "/")}><ArrowBackRounded/></Button><Breadcrumbs>{path.split("/").filter(Boolean).reduce<{ label: string; path: string }[]>((all, part) => [...all, { label: part, path: `${all.at(-1)?.path || ""}/${part}` }], [{ label: host.name, path: "/" }]).map((part) => <Link key={part.path} component="button" color="inherit" onClick={() => setPath(part.path)}>{part.label}</Link>)}</Breadcrumbs></Stack></Paper>
    <Paper variant="outlined" sx={{ flex: 1, overflow: "auto" }} onContextMenu={(e) => { e.preventDefault(); setMenu({ x: e.clientX, y: e.clientY }); }}>{loading && <LinearProgress/>}<Table stickyHeader><TableHead><TableRow><TableCell padding="checkbox"><Checkbox inputProps={{ "aria-label": "选择所有文件" }} indeterminate={selected.length > 0 && selected.length < entries.length} checked={entries.length > 0 && selected.length === entries.length} onChange={(e) => setSelected(e.target.checked ? entries.map((x) => x.path) : [])}/></TableCell><TableCell>名称</TableCell><TableCell>大小</TableCell><TableCell>权限</TableCell><TableCell>修改时间</TableCell></TableRow></TableHead><TableBody>{entries.map((entry) => <TableRow key={entry.path} hover selected={selected.includes(entry.path)} onContextMenu={(e) => { e.preventDefault(); e.stopPropagation(); setMenu({ x: e.clientX, y: e.clientY, entry }); }} onDoubleClick={() => openEntry(entry)}><TableCell padding="checkbox"><Checkbox inputProps={{ "aria-label": `选择 ${entry.name}` }} checked={selected.includes(entry.path)} onChange={() => toggle(entry.path)}/></TableCell><TableCell><Stack direction="row" alignItems="center" spacing={1}>{entry.kind === "directory" ? <FolderRounded color="primary"/> : <InsertDriveFileRounded color="disabled"/>}<Link component="button" variant="body2" underline="hover" color="inherit" onClick={() => entry.kind === "directory" ? openEntry(entry) : toggle(entry.path)}>{entry.name}</Link></Stack></TableCell><TableCell>{entry.kind === "directory" ? "—" : formatBytes(entry.size)}</TableCell><TableCell className="mono">{entry.permissions || "—"}</TableCell><TableCell>{entry.modifiedAt ? new Date(entry.modifiedAt).toLocaleString() : "—"}</TableCell></TableRow>)}</TableBody></Table></Paper>
    <Menu open={Boolean(menu)} onClose={() => setMenu(null)} anchorReference="anchorPosition" anchorPosition={menu ? { top: menu.y, left: menu.x } : undefined}><MenuItem onClick={() => { if (menu?.entry) openEntry(menu.entry); setMenu(null); }} disabled={!menu?.entry || menu.entry.kind !== "directory"}>打开目录</MenuItem><MenuItem onClick={() => { if (menu?.entry) void download([menu.entry.path]); setMenu(null); }} disabled={!menu?.entry}>下载</MenuItem><MenuItem onClick={() => { if (menu?.entry) setClipboard({ hostId: host.id, paths: [menu.entry.path] }); setMenu(null); }}>复制</MenuItem><MenuItem onClick={() => { if (menu?.entry) { setRename(menu.entry); setNewName(menu.entry.name); } setMenu(null); }} disabled={!menu?.entry}>重命名</MenuItem><MenuItem onClick={() => { if (menu?.entry) void remove([menu.entry.path]); setMenu(null); }} disabled={!menu?.entry} sx={{ color: "error.main" }}>删除</MenuItem><MenuItem onClick={() => { setMenu(null); load(); }}>刷新</MenuItem></Menu>
    <Dialog open={Boolean(conflict)} onClose={() => setConflict(undefined)} fullWidth maxWidth="xs"><DialogTitle>{conflict?.title}</DialogTitle><DialogContent><Typography variant="body2" color="text.secondary">选择文件已存在时的处理方式。续传会先校验已有内容，发现不一致将终止操作。</Typography></DialogContent><DialogActions><Button onClick={() => setConflict(undefined)}>取消</Button><Button onClick={() => { const action = conflict; setConflict(undefined); if (action) void action.run("skip"); }}>跳过</Button><Button onClick={() => { const action = conflict; setConflict(undefined); if (action) void action.run("rename"); }}>重命名</Button><Button onClick={() => { const action = conflict; setConflict(undefined); if (action) void action.run("resume"); }}>续传</Button><Button variant="contained" color="warning" onClick={() => { const action = conflict; setConflict(undefined); if (action) void action.run("overwrite"); }}>覆盖</Button></DialogActions></Dialog>
    <Dialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(undefined)}><DialogTitle>永久删除远程项目？</DialogTitle><DialogContent><Typography>将删除 {deleteTarget?.length || 0} 项，目录中的内容也会被删除，此操作无法恢复。</Typography></DialogContent><DialogActions><Button onClick={() => setDeleteTarget(undefined)}>取消</Button><Button color="error" variant="contained" onClick={() => void performRemove()}>永久删除</Button></DialogActions></Dialog>
    <Dialog open={!!rename} onClose={() => setRename(undefined)}><DialogTitle>重命名</DialogTitle><DialogContent><TextField autoFocus fullWidth label="新文件名" value={newName} onChange={(e) => setNewName(e.target.value)} sx={{ mt: 1 }}/></DialogContent><DialogActions><Button onClick={() => setRename(undefined)}>取消</Button><Button variant="contained" startIcon={<DriveFileRenameOutlineRounded/>} onClick={submitRename}>保存</Button></DialogActions></Dialog><Dialog open={mkdirOpen} onClose={() => setMkdirOpen(false)}><DialogTitle>新建目录</DialogTitle><DialogContent><TextField autoFocus fullWidth label="目录名" value={folderName} onChange={(e) => setFolderName(e.target.value)} sx={{ mt: 1 }}/></DialogContent><DialogActions><Button onClick={() => setMkdirOpen(false)}>取消</Button><Button variant="contained" onClick={submitMkdir}>创建</Button></DialogActions></Dialog>
  </Stack>;
}
function ChipCount({ count }: { count: number }) { return count ? <Typography variant="caption" color="text.secondary">已选 {count} 项</Typography> : null; }

function validName(value: string) { const name = value.trim(); return Boolean(name) && name !== "." && name !== ".." && !/[\/\\\x00-\x1f\x7f]/.test(name); }
